services:
  - type: web
    name: linebot-dbm
    env: node
    repo: https://github.com/Thomas-Chiu/linebot_dbm
    buildCommand: cd examples/echo-bot;npm install
    startCommand: cd examples/echo-bot;npm run start
    plan: free
    autoDeploy: false
    envVars:
      - key: CHANNEL_ACCESS_TOKEN
        sync: false
      - key: CHANNEL_SECRET
        sync: false
